const $=id=>document.getElementById(id);let config;function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3800)}function showUser(name){$('accountName').textContent=name||'Se connecter';document.querySelector('.avatar').textContent=(name||'?')[0].toUpperCase();$('logoutButton').hidden=!name}function remember(){return $('rememberSession').checked}function loginCredentials(){return{username:$('loginName').value.trim(),password:$('loginPassword').value,rememberSession:remember()}}function registerCredentials(){return{username:$('registerName').value.trim(),password:$('registerPassword').value,rememberSession:remember()}}
async function init(){config=await window.launcher.settings();$('loginDialog').addEventListener('cancel',e=>e.preventDefault());if(config.authMode&&config.rememberSession!==false){showUser(config.displayName)}else{if(config.authMode)await window.launcher.logout();showUser('');$('loginDialog').showModal()}}
$('account').onclick=async()=>{config=await window.launcher.settings();if(!config.authMode){$('loginDialog').showModal();return}const account=await window.launcher.account();$('accountMode').textContent=account.mode==='microsoft'?'COMPTE MICROSOFT':'COMPTE EPSILON';$('accountUsername').value=account.username||'';$('accountUsername').disabled=account.mode==='microsoft';$('passwordFields').hidden=account.mode==='microsoft';$('skinFields').hidden=account.mode==='microsoft';$('officialSkin').hidden=account.mode!=='microsoft';$('accountDialog').showModal()};
$('microsoftLogin').onclick=async()=>{try{toast('Ouverture de la connexion Microsoft…');const r=await window.launcher.loginMicrosoft(remember());showUser(r.name);$('loginDialog').close();toast('Connexion Microsoft réussie')}catch(e){toast('Connexion Microsoft : '+e.message)}};
$('epsilonLogin').onclick=async()=>{try{const r=await window.launcher.loginEpsilon(loginCredentials());showUser(r.name);$('loginPassword').value='';$('loginDialog').close();toast('Connexion EPSILON réussie')}catch(e){toast(e.message)}};$('epsilonRegister').onclick=async()=>{try{if($('registerPassword').value!==$('registerConfirm').value)throw new Error('Les mots de passe sont différents.');const r=await window.launcher.registerEpsilon(registerCredentials());showUser(r.name);$('registerPassword').value='';$('registerConfirm').value='';$('loginDialog').close();toast('Compte EPSILON créé')}catch(e){toast(e.message)}};
$('logoutButton').onclick=async()=>{try{await window.launcher.logout();config=await window.launcher.settings();showUser('');$('loginDialog').close();toast('Vous êtes déconnecté')}catch(e){toast(e.message)}};
$('closeAccount').onclick=()=>$('accountDialog').close();$('accountLogout').onclick=async()=>{await window.launcher.logout();config=await window.launcher.settings();showUser('');$('accountDialog').close();$('loginDialog').showModal();toast('Vous êtes déconnecté')};
$('chooseSkin').onclick=async()=>{try{const skin=await window.launcher.chooseSkin();if(skin){$('skinPreview').src=skin.preview;$('skinPreview').hidden=false;toast('Skin enregistré pour EpsilonLauncher')}}catch(e){toast(e.message)}};
$('saveAccount').onclick=async()=>{try{if($('newPassword').value!==$('newPasswordConfirm').value)throw new Error('Les nouveaux mots de passe sont différents.');const result=await window.launcher.updateAccount({username:$('accountUsername').value.trim(),oldPassword:$('oldPassword').value,newPassword:$('newPassword').value});showUser(result.username);$('oldPassword').value='';$('newPassword').value='';$('newPasswordConfirm').value='';$('accountDialog').close();toast('Compte mis à jour')}catch(e){toast(e.message)}};
$('playButton').onclick=async()=>{config=await window.launcher.settings();if(!config.authMode){$('loginDialog').showModal();return}await window.launcher.openEpsilon()};$('openFolder').onclick=()=>window.launcher.openInstance();init().catch(e=>toast(e.message));
